# Generated by Django 4.0.5 on 2022-07-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familiar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='nombre',
            new_name='nombref',
        ),
    ]
